//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graxei.Transversais.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graxei.Transversais.Idiomas.Erros", typeof(Erros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não existe ou senha é inválida.
        /// </summary>
        public static string AutenticacaoEmail {
            get {
                return ResourceManager.GetString("AutenticacaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválida.
        /// </summary>
        public static string AutenticacaoLogin {
            get {
                return ResourceManager.GetString("AutenticacaoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do bairro deve ser informado.
        /// </summary>
        public static string BairroNomeNulo {
            get {
                return ResourceManager.GetString("BairroNomeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço incompleto: bairro faltando.
        /// </summary>
        public static string BairroNulo {
            get {
                return ResourceManager.GetString("BairroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da categoria deve ser informado.
        /// </summary>
        public static string CategoriaNomeNulo {
            get {
                return ResourceManager.GetString("CategoriaNomeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço incompleto: cidade faltando.
        /// </summary>
        public static string CidadeNulo {
            get {
                return ResourceManager.GetString("CidadeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória.
        /// </summary>
        public static string DescricaoNula {
            get {
                return ResourceManager.GetString("DescricaoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da unidade de medida é obrigatória.
        /// </summary>
        public static string DescricaoUnidadeMedidaNula {
            get {
                return ResourceManager.GetString("DescricaoUnidadeMedidaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço deve pertencer a uma loja.
        /// </summary>
        public static string EnderecoLojaNulo {
            get {
                return ResourceManager.GetString("EnderecoLojaNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço incompleto: preencha o número.
        /// </summary>
        public static string EnderecoNumeroNulo {
            get {
                return ResourceManager.GetString("EnderecoNumeroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço incompleto: estado faltando.
        /// </summary>
        public static string EstadoNulo {
            get {
                return ResourceManager.GetString("EstadoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço incompleto: preencha o logradouro.
        /// </summary>
        public static string LogradouroNulo {
            get {
                return ResourceManager.GetString("LogradouroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja inválida: atributos obrigatórios têm valor nulo.
        /// </summary>
        public static string LojaInvalida {
            get {
                return ResourceManager.GetString("LojaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta loja já existe.
        /// </summary>
        public static string LojaJaExiste {
            get {
                return ResourceManager.GetString("LojaJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da loja deve ser informado.
        /// </summary>
        public static string LojaNomeNulo {
            get {
                return ResourceManager.GetString("LojaNomeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja nula.
        /// </summary>
        public static string LojaNula {
            get {
                return ResourceManager.GetString("LojaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A loja é obrigatória.
        /// </summary>
        public static string LojaNulo {
            get {
                return ResourceManager.GetString("LojaNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A loja não pode ser salva sem uma associação com algum usuário.
        /// </summary>
        public static string LojaSalvarInvalido {
            get {
                return ResourceManager.GetString("LojaSalvarInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço deve ser informado.
        /// </summary>
        public static string PrecoNulo {
            get {
                return ResourceManager.GetString("PrecoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem atributos repetidos para este produto.
        /// </summary>
        public static string ProdutoAtributosRepetidos {
            get {
                return ResourceManager.GetString("ProdutoAtributosRepetidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do produto é obrigatória.
        /// </summary>
        public static string ProdutoDescricaoNulo {
            get {
                return ResourceManager.GetString("ProdutoDescricaoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto já existe.
        /// </summary>
        public static string ProdutoExiste {
            get {
                return ResourceManager.GetString("ProdutoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fabricante é obrigatório.
        /// </summary>
        public static string ProdutoFabricanteNulo {
            get {
                return ResourceManager.GetString("ProdutoFabricanteNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto já pertence a essa loja.
        /// </summary>
        public static string ProdutoMesmaLoja {
            get {
                return ResourceManager.GetString("ProdutoMesmaLoja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto é obrigatório.
        /// </summary>
        public static string ProdutoNulo {
            get {
                return ResourceManager.GetString("ProdutoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto é obrigatório em ProdutoVendedor.
        /// </summary>
        public static string ProdutoPaiNulo {
            get {
                return ResourceManager.GetString("ProdutoPaiNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço deve ser maior que zero.
        /// </summary>
        public static string ProdutoPrecoInvalido {
            get {
                return ResourceManager.GetString("ProdutoPrecoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla da unidade de medida é obrigatória.
        /// </summary>
        public static string SiglaUnidadeMedidaNula {
            get {
                return ResourceManager.GetString("SiglaUnidadeMedidaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade de entrada é obrigatória.
        /// </summary>
        public static string UnidadeEntradaNulo {
            get {
                return ResourceManager.GetString("UnidadeEntradaNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade de saída é obrigatória.
        /// </summary>
        public static string UnidadeSaidaNulo {
            get {
                return ResourceManager.GetString("UnidadeSaidaNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário deve ser informado.
        /// </summary>
        public static string UsuarioLoginNulo {
            get {
                return ResourceManager.GetString("UsuarioLoginNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário {0} não encontrado.
        /// </summary>
        public static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero.
        /// </summary>
        public static string ValorMaiorZero {
            get {
                return ResourceManager.GetString("ValorMaiorZero", resourceCulture);
            }
        }
    }
}
