//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graxei.Transversais.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrosInternos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrosInternos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graxei.Transversais.Idiomas.ErrosInternos", typeof(ErrosInternos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento &apos;Bairro&apos; é nulo.
        /// </summary>
        public static string ArgumentoBairroNulo {
            get {
                return ResourceManager.GetString("ArgumentoBairroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento &apos;Cidade&apos; é nulo.
        /// </summary>
        public static string ArgumentoCidadeNulo {
            get {
                return ResourceManager.GetString("ArgumentoCidadeNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento &apos;Estado&apos; é nulo.
        /// </summary>
        public static string ArgumentoEstadoNulo {
            get {
                return ResourceManager.GetString("ArgumentoEstadoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Bairro é inválido.
        /// </summary>
        public static string BairroInvalido {
            get {
                return ResourceManager.GetString("BairroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Cidade é inválida.
        /// </summary>
        public static string CidadeInvalida {
            get {
                return ResourceManager.GetString("CidadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro é nulo.
        /// </summary>
        public static string EnderecoBairroNulo {
            get {
                return ResourceManager.GetString("EnderecoBairroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A loja é nula.
        /// </summary>
        public static string EnderecoLojaNulo {
            get {
                return ResourceManager.GetString("EnderecoLojaNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado é inválido.
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListaLojas não pode ser nulo ao criar links de paginação.
        /// </summary>
        public static string ListasLojasNula {
            get {
                return ResourceManager.GetString("ListasLojasNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelState inválido.
        /// </summary>
        public static string ModelStateInvalido {
            get {
                return ResourceManager.GetString("ModelStateInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome ou estado da cidade não pode ser alterado.
        /// </summary>
        public static string ProibidoAlterarCidade {
            get {
                return ResourceManager.GetString("ProibidoAlterarCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O total da lista não pode ser menor que o item atual.
        /// </summary>
        public static string TotalMenorQueAtual {
            get {
                return ResourceManager.GetString("TotalMenorQueAtual", resourceCulture);
            }
        }
    }
}
