//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graxei.Transversais.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validacoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validacoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graxei.Transversais.Idiomas.Validacoes", typeof(Validacoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro é obrigatório.
        /// </summary>
        public static string BairroObrigatorio {
            get {
                return ResourceManager.GetString("BairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatória.
        /// </summary>
        public static string CidadeObrigatoria {
            get {
                return ResourceManager.GetString("CidadeObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório.
        /// </summary>
        public static string EstadoObrigatorio {
            get {
                return ResourceManager.GetString("EstadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro é obrigatório.
        /// </summary>
        public static string LogradouroObrigatorio {
            get {
                return ResourceManager.GetString("LogradouroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da loja deve ser preenchido.
        /// </summary>
        public static string NomeLojaObrigatorio {
            get {
                return ResourceManager.GetString("NomeLojaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório.
        /// </summary>
        public static string NumeroObrigatorio {
            get {
                return ResourceManager.GetString("NumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a senha.
        /// </summary>
        public static string SenhaObrigatoria {
            get {
                return ResourceManager.GetString("SenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla é obrigatória.
        /// </summary>
        public static string SiglaObrigatoria {
            get {
                return ResourceManager.GetString("SiglaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número máximo de caracteres é de 150.
        /// </summary>
        public static string TamanhoMaximo150 {
            get {
                return ResourceManager.GetString("TamanhoMaximo150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número máximo de caracteres é de 250.
        /// </summary>
        public static string TamanhoMaximo250 {
            get {
                return ResourceManager.GetString("TamanhoMaximo250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho máximo permitido é de 50 caracteres .
        /// </summary>
        public static string TamanhoMaximo50 {
            get {
                return ResourceManager.GetString("TamanhoMaximo50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número máximo de telefones para esta loja foi atingido.
        /// </summary>
        public static string TamanhoMaximoTelefones {
            get {
                return ResourceManager.GetString("TamanhoMaximoTelefones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório.
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o nome do usuário ou e-mail .
        /// </summary>
        public static string UsuarioEmailObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioEmailObrigatorio", resourceCulture);
            }
        }
    }
}
